### ISSUE TITLE
RecursiveComparisonDifferenceCalculator fails with IllegalStateException: Duplicate key

### ISSUE THREAD

**Issue by realdadfish** [assertj/assertj-core#2250]
#### Summary

I'm recursively comparing Android's `Spanned` implementations (`SpannableString`, `SpannableStringBuilder`). The issue is that the `Span` implementations such as [`StyleSpan`](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/text/style/StyleSpan.java?q=StyleSpan) do not come with an `equals` implementation, so they're identity-compared usually, which is useless.

When trying to compare two such instances through the means of `RecursiveComparisonDifferenceCalculator`, I get the following exception:

```
java.lang.IllegalStateException: Duplicate key 1 (attempted merging values android.text.style.StyleSpan@23614f48=0 and android.text.style.StyleSpan@38cf293b=1)
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.IdentityHashMap$EntrySpliterator.forEachRemaining(IdentityHashMap.java:1563)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.assertj.core.api.recursive.comparison.RecursiveComparisonDifferenceCalculator.compareUnorderedMap(RecursiveComparisonDifferenceCalculator.java:491)
	at org.assertj.core.api.recursive.comparison.RecursiveComparisonDifferenceCalculator.determineDifferences(RecursiveComparisonDifferenceCalculator.java:255)
	at org.assertj.core.api.recursive.comparison.RecursiveComparisonDifferenceCalculator.determineDifferences(RecursiveComparisonDifferenceCalculator.java:185)
...
```

#### Example

A simple example (Android SDK required or Robolectric):

```kotlin
val left = Html.fromHtml("<b>This is a test</b>")
val right = Html.fromHtml("<b>This is a test</b>")
val calculator = RecursiveComparisonDifferenceCalculator()
calculator.determineDifferences(left, right, RecursiveComparisonConfiguration.builder().build())
```

**Comment by scordio** [comment]
Hi @realdadfish, thanks for the bug report. Would you have the chance to provide a minimal example as a GitHub project?

**Comment by realdadfish** [comment]
Yes, I will try my best :)

**Comment by realdadfish** [comment]
I couldn't reproduce this with an isolated setup, yet, so I'm closing this one. Sorry.

**Comment by joel-costigliola** [comment]
Thanks for trying @realdadfish.
