### ISSUE TITLE
zipSatisfy output part of stack trace for failures

### ISSUE THREAD

**Issue by anuraaga** [assertj/assertj-core#2300]
#### Summary
Currently `zipSatisfy` seems to collect only assertion exception messages and outputs them.

https://github.com/assertj/assertj-core/blob/main/src/main/java/org/assertj/core/internal/Iterables.java#L1254

It would be helpful if the stacktrace was collected too - in particular, even one or two lines of stack trace can really help understand an assertion failure if the message is not a great assertion message. In particular, it's quite easy to end up with an `Expecting actual not to be null` due to an `isNotNull` call in a higher-level assertion, and with no stack trace this can't be debugged.

#### Example

```java
assertThat(strings).zipSatisfy(str -> assertThat(str).startsWith("cat"))
```

This will not provide any pointer to the real failure if `str` is null, while if the stack trace is printed (assuming it is one in many assertions) there will be great context.

**Comment by anuraaga** [comment]
Also, it's not directly related to this issue but is a part of "how to render zipSatisfy" - I noticed that nested zipSatisfy render somewhat poorly since they end up printing top-down, even though we'd like the actual assertion failure to be at the top of a message. For example, when nesting two zipSatisfies it looks like this

```
Caused by: java.lang.AssertionError: 
Expecting zipped elements of:
  [[TestSpanData{name=HTTP GET, kind=CLIENT, spanContext=ImmutableSpanContext{traceId=bcd84bfefb397c0c02818034b7674eef, spanId=6b0ee7ede25b1f05, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}, status=ImmutableStatusData{statusCode=UNSET, description=}, startEpochNanos=1627458288255178292, attributes={http.flavor="1.1", http.method="GET", http.status_code=200, http.url="http://localhost:50139/success", net.peer.name="localhost", net.peer.port=50139, net.transport="ip_tcp"}, events=[], links=[], endEpochNanos=1627458288795323042, totalRecordedEvents=0, totalRecordedLinks=0, totalAttributeCount=7, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=com.splunk.javaagent.khttp-0.1, version=, schemaUrl=null}, resource=Resource{schemaUrl=null, attributes={host.arch="x86_64", host.name="147dda398a63.ant.amazon.com", os.description="Mac OS X 10.16", os.type="darwin", process.command_line="/Users/aanuraag/Library/Java/JavaVirtualMachines/adopt-openjdk-11.0.10/Contents/Home:bin:java -Djavax.net.ssl.trustStore=/Users/aanuraag/git/splunk-otel-java/testing/common/src/misc/testing-keystore.p12 -Djavax.net.ssl.trustStorePassword=testing -Dorg.gradle.internal.worker.tmpdir=/Users/aanuraag/git/splunk-otel-java/instrumentation/khttp/build/tmp/test/work -Dorg.gradle.native=false -Dotel.javaagent.add-thread-details=false -Dotel.javaagent.debug=true -Dotel.javaagent.experimental.initializer.jar=/Users/aanuraag/git/splunk-otel-java/instrumentation/khttp/build/libs/agent-testing.jar -Dotel.javaagent.testing.additional-library-ignores.enabled=false -Dotel.javaagent.testing.fail-on-context-leak=true -Dotel.javaagent.testing.transform-safe-logging.enabled=true -javaagent:/Users/aanuraag/git/splunk-otel-java/testing/agent-for-testing/build/libs/agent-for-testing-1.3.0-SNAPSHOT-all.jar --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=JP -Duser.language=en -Duser.variant -ea", process.executable.path="/Users/aanuraag/Library/Java/JavaVirtualMachines/adopt-openjdk-11.0.10/Contents/Home:bin:java", process.pid=68181, process.runtime.description="AdoptOpenJDK OpenJDK 64-Bit Server VM 11.0.10+9", process.runtime.name="OpenJDK Runtime Environment", process.runtime.version="11.0.10+9", service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.4.1"}}, internalHasEnded=true},
    TestSpanData{name=test-http-server, kind=SERVER, spanContext=ImmutableSpanContext{traceId=bcd84bfefb397c0c02818034b7674eef, spanId=5ab379fc04e83f19, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=bcd84bfefb397c0c02818034b7674eef, spanId=6b0ee7ede25b1f05, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, status=ImmutableStatusData{statusCode=UNSET, description=}, startEpochNanos=1627458288694288368, attributes={}, events=[], links=[], endEpochNanos=1627458288694335595, totalRecordedEvents=0, totalRecordedLinks=0, totalAttributeCount=0, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=test, version=, schemaUrl=null}, resource=Resource{schemaUrl=null, attributes={host.arch="x86_64", host.name="147dda398a63.ant.amazon.com", os.description="Mac OS X 10.16", os.type="darwin", process.command_line="/Users/aanuraag/Library/Java/JavaVirtualMachines/adopt-openjdk-11.0.10/Contents/Home:bin:java -Djavax.net.ssl.trustStore=/Users/aanuraag/git/splunk-otel-java/testing/common/src/misc/testing-keystore.p12 -Djavax.net.ssl.trustStorePassword=testing -Dorg.gradle.internal.worker.tmpdir=/Users/aanuraag/git/splunk-otel-java/instrumentation/khttp/build/tmp/test/work -Dorg.gradle.native=false -Dotel.javaagent.add-thread-details=false -Dotel.javaagent.debug=true -Dotel.javaagent.experimental.initializer.jar=/Users/aanuraag/git/splunk-otel-java/instrumentation/khttp/build/libs/agent-testing.jar -Dotel.javaagent.testing.additional-library-ignores.enabled=false -Dotel.javaagent.testing.fail-on-context-leak=true -Dotel.javaagent.testing.transform-safe-logging.enabled=true -javaagent:/Users/aanuraag/git/splunk-otel-java/testing/agent-for-testing/build/libs/agent-for-testing-1.3.0-SNAPSHOT-all.jar --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=JP -Duser.language=en -Duser.variant -ea", process.executable.path="/Users/aanuraag/Library/Java/JavaVirtualMachines/adopt-openjdk-11.0.10/Contents/Home:bin:java", process.pid=68181, process.runtime.description="AdoptOpenJDK OpenJDK 64-Bit Server VM 11.0.10+9", process.runtime.name="OpenJDK Runtime Environment", process.runtime.version="11.0.10+9", service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.4.1"}}, internalHasEnded=true}]]
and:
  [io.opentelemetry.instrumentation.testing.junit.http.AbstractHttpClientTest$$Lambda$697/0x000000080072f840@26044a0f]
to satisfy given requirements but these zipped elements did not:

- ([TestSpanData{name=HTTP GET, kind=CLIENT, spanContext=ImmutableSpanContext{traceId=bcd84bfefb397c0c02818034b7674eef, spanId=6b0ee7ede25b1f05, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}, status=ImmutableStatusData{statusCode=UNSET, description=}, startEpochNanos=1627458288255178292, attributes={http.flavor="1.1", http.method="GET", http.status_code=200, http.url="http://localhost:50139/success", net.peer.name="localhost", net.peer.port=50139, net.transport="ip_tcp"}, events=[], links=[], endEpochNanos=1627458288795323042, totalRecordedEvents=0, totalRecordedLinks=0, totalAttributeCount=7, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=com.splunk.javaagent.khttp-0.1, version=, schemaUrl=null}, resource=Resource{schemaUrl=null, attributes={host.arch="x86_64", host.name="147dda398a63.ant.amazon.com", os.description="Mac OS X 10.16", os.type="darwin", process.command_line="/Users/aanuraag/Library/Java/JavaVirtualMachines/adopt-openjdk-11.0.10/Contents/Home:bin:java -Djavax.net.ssl.trustStore=/Users/aanuraag/git/splunk-otel-java/testing/common/src/misc/testing-keystore.p12 -Djavax.net.ssl.trustStorePassword=testing -Dorg.gradle.internal.worker.tmpdir=/Users/aanuraag/git/splunk-otel-java/instrumentation/khttp/build/tmp/test/work -Dorg.gradle.native=false -Dotel.javaagent.add-thread-details=false -Dotel.javaagent.debug=true -Dotel.javaagent.experimental.initializer.jar=/Users/aanuraag/git/splunk-otel-java/instrumentation/khttp/build/libs/agent-testing.jar -Dotel.javaagent.testing.additional-library-ignores.enabled=false -Dotel.javaagent.testing.fail-on-context-leak=true -Dotel.javaagent.testing.transform-safe-logging.enabled=true -javaagent:/Users/aanuraag/git/splunk-otel-java/testing/agent-for-testing/build/libs/agent-for-testing-1.3.0-SNAPSHOT-all.jar --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=JP -Duser.language=en -Duser.variant -ea", process.executable.path="/Users/aanuraag/Library/Java/JavaVirtualMachines/adopt-openjdk-11.0.10/Contents/Home:bin:java", process.pid=68181, process.runtime.description="AdoptOpenJDK OpenJDK 64-Bit Server VM 11.0.10+9", process.runtime.name="OpenJDK Runtime Environment", process.runtime.version="11.0.10+9", service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.4.1"}}, internalHasEnded=true},
    TestSpanData{name=test-http-server, kind=SERVER, spanContext=ImmutableSpanContext{traceId=bcd84bfefb397c0c02818034b7674eef, spanId=5ab379fc04e83f19, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=bcd84bfefb397c0c02818034b7674eef, spanId=6b0ee7ede25b1f05, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, status=ImmutableStatusData{statusCode=UNSET, description=}, startEpochNanos=1627458288694288368, attributes={}, events=[], links=[], endEpochNanos=1627458288694335595, totalRecordedEvents=0, totalRecordedLinks=0, totalAttributeCount=0, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=test, version=, schemaUrl=null}, resource=Resource{schemaUrl=null, attributes={host.arch="x86_64", host.name="147dda398a63.ant.amazon.com", os.description="Mac OS X 10.16", os.type="darwin", process.command_line="/Users/aanuraag/Library/Java/JavaVirtualMachines/adopt-openjdk-11.0.10/Contents/Home:bin:java -Djavax.net.ssl.trustStore=/Users/aanuraag/git/splunk-otel-java/testing/common/src/misc/testing-keystore.p12 -Djavax.net.ssl.trustStorePassword=testing -Dorg.gradle.internal.worker.tmpdir=/Users/aanuraag/git/splunk-otel-java/instrumentation/khttp/build/tmp/test/work -Dorg.gradle.native=false -Dotel.javaagent.add-thread-details=false -Dotel.javaagent.debug=true -Dotel.javaagent.experimental.initializer.jar=/Users/aanuraag/git/splunk-otel-java/instrumentation/khttp/build/libs/agent-testing.jar -Dotel.javaagent.testing.additional-library-ignores.enabled=false -Dotel.javaagent.testing.fail-on-context-leak=true -Dotel.javaagent.testing.transform-safe-logging.enabled=true -javaagent:/Users/aanuraag/git/splunk-otel-java/testing/agent-for-testing/build/libs/agent-for-testing-1.3.0-SNAPSHOT-all.jar --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=JP -Duser.language=en -Duser.variant -ea", process.executable.path="/Users/aanuraag/Library/Java/JavaVirtualMachines/adopt-openjdk-11.0.10/Contents/Home:bin:java", process.pid=68181, process.runtime.description="AdoptOpenJDK OpenJDK 64-Bit Server VM 11.0.10+9", process.runtime.name="OpenJDK Runtime Environment", process.runtime.version="11.0.10+9", service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.4.1"}}, internalHasEnded=true}], io.opentelemetry.instrumentation.testing.junit.http.AbstractHttpClientTest$$Lambda$697/0x000000080072f840@26044a0f)
error: 
Expecting zipped elements of:
  [TestSpanData{name=HTTP GET, kind=CLIENT, spanContext=ImmutableSpanContext{traceId=bcd84bfefb397c0c02818034b7674eef, spanId=6b0ee7ede25b1f05, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}, status=ImmutableStatusData{statusCode=UNSET, description=}, startEpochNanos=1627458288255178292, attributes={http.flavor="1.1", http.method="GET", http.status_code=200, http.url="http://localhost:50139/success", net.peer.name="localhost", net.peer.port=50139, net.transport="ip_tcp"}, events=[], links=[], endEpochNanos=1627458288795323042, totalRecordedEvents=0, totalRecordedLinks=0, totalAttributeCount=7, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=com.splunk.javaagent.khttp-0.1, version=, schemaUrl=null}, resource=Resource{schemaUrl=null, attributes={host.arch="x86_64", host.name="147dda398a63.ant.amazon.com", os.description="Mac OS X 10.16", os.type="darwin", process.command_line="/Users/aanuraag/Library/Java/JavaVirtualMachines/adopt-openjdk-11.0.10/Contents/Home:bin:java -Djavax.net.ssl.trustStore=/Users/aanuraag/git/splunk-otel-java/testing/common/src/misc/testing-keystore.p12 -Djavax.net.ssl.trustStorePassword=testing -Dorg.gradle.internal.worker.tmpdir=/Users/aanuraag/git/splunk-otel-java/instrumentation/khttp/build/tmp/test/work -Dorg.gradle.native=false -Dotel.javaagent.add-thread-details=false -Dotel.javaagent.debug=true -Dotel.javaagent.experimental.initializer.jar=/Users/aanuraag/git/splunk-otel-java/instrumentation/khttp/build/libs/agent-testing.jar -Dotel.javaagent.testing.additional-library-ignores.enabled=false -Dotel.javaagent.testing.fail-on-context-leak=true -Dotel.javaagent.testing.transform-safe-logging.enabled=true -javaagent:/Users/aanuraag/git/splunk-otel-java/testing/agent-for-testing/build/libs/agent-for-testing-1.3.0-SNAPSHOT-all.jar --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=JP -Duser.language=en -Duser.variant -ea", process.executable.path="/Users/aanuraag/Library/Java/JavaVirtualMachines/adopt-openjdk-11.0.10/Contents/Home:bin:java", process.pid=68181, process.runtime.description="AdoptOpenJDK OpenJDK 64-Bit Server VM 11.0.10+9", process.runtime.name="OpenJDK Runtime Environment", process.runtime.version="11.0.10+9", service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.4.1"}}, internalHasEnded=true},
    TestSpanData{name=test-http-server, kind=SERVER, spanContext=ImmutableSpanContext{traceId=bcd84bfefb397c0c02818034b7674eef, spanId=5ab379fc04e83f19, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=bcd84bfefb397c0c02818034b7674eef, spanId=6b0ee7ede25b1f05, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, status=ImmutableStatusData{statusCode=UNSET, description=}, startEpochNanos=1627458288694288368, attributes={}, events=[], links=[], endEpochNanos=1627458288694335595, totalRecordedEvents=0, totalRecordedLinks=0, totalAttributeCount=0, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=test, version=, schemaUrl=null}, resource=Resource{schemaUrl=null, attributes={host.arch="x86_64", host.name="147dda398a63.ant.amazon.com", os.description="Mac OS X 10.16", os.type="darwin", process.command_line="/Users/aanuraag/Library/Java/JavaVirtualMachines/adopt-openjdk-11.0.10/Contents/Home:bin:java -Djavax.net.ssl.trustStore=/Users/aanuraag/git/splunk-otel-java/testing/common/src/misc/testing-keystore.p12 -Djavax.net.ssl.trustStorePassword=testing -Dorg.gradle.internal.worker.tmpdir=/Users/aanuraag/git/splunk-otel-java/instrumentation/khttp/build/tmp/test/work -Dorg.gradle.native=false -Dotel.javaagent.add-thread-details=false -Dotel.javaagent.debug=true -Dotel.javaagent.experimental.initializer.jar=/Users/aanuraag/git/splunk-otel-java/instrumentation/khttp/build/libs/agent-testing.jar -Dotel.javaagent.testing.additional-library-ignores.enabled=false -Dotel.javaagent.testing.fail-on-context-leak=true -Dotel.javaagent.testing.transform-safe-logging.enabled=true -javaagent:/Users/aanuraag/git/splunk-otel-java/testing/agent-for-testing/build/libs/agent-for-testing-1.3.0-SNAPSHOT-all.jar --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=JP -Duser.language=en -Duser.variant -ea", process.executable.path="/Users/aanuraag/Library/Java/JavaVirtualMachines/adopt-openjdk-11.0.10/Contents/Home:bin:java", process.pid=68181, process.runtime.description="AdoptOpenJDK OpenJDK 64-Bit Server VM 11.0.10+9", process.runtime.name="OpenJDK Runtime Environment", process.runtime.version="11.0.10+9", service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.4.1"}}, internalHasEnded=true}]
and:
  [io.opentelemetry.instrumentation.testing.junit.http.AbstractHttpClientTest$$Lambda$726/0x0000000800798c40@18d02035,
    io.opentelemetry.instrumentation.testing.junit.http.AbstractHttpClientTest$$Lambda$727/0x0000000800799040@3526e55b]
to satisfy given requirements but these zipped elements did not:

- (TestSpanData{name=HTTP GET, kind=CLIENT, spanContext=ImmutableSpanContext{traceId=bcd84bfefb397c0c02818034b7674eef, spanId=6b0ee7ede25b1f05, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}, status=ImmutableStatusData{statusCode=UNSET, description=}, startEpochNanos=1627458288255178292, attributes={http.flavor="1.1", http.method="GET", http.status_code=200, http.url="http://localhost:50139/success", net.peer.name="localhost", net.peer.port=50139, net.transport="ip_tcp"}, events=[], links=[], endEpochNanos=1627458288795323042, totalRecordedEvents=0, totalRecordedLinks=0, totalAttributeCount=7, instrumentationLibraryInfo=InstrumentationLibraryInfo{name=com.splunk.javaagent.khttp-0.1, version=, schemaUrl=null}, resource=Resource{schemaUrl=null, attributes={host.arch="x86_64", host.name="147dda398a63.ant.amazon.com", os.description="Mac OS X 10.16", os.type="darwin", process.command_line="/Users/aanuraag/Library/Java/JavaVirtualMachines/adopt-openjdk-11.0.10/Contents/Home:bin:java -Djavax.net.ssl.trustStore=/Users/aanuraag/git/splunk-otel-java/testing/common/src/misc/testing-keystore.p12 -Djavax.net.ssl.trustStorePassword=testing -Dorg.gradle.internal.worker.tmpdir=/Users/aanuraag/git/splunk-otel-java/instrumentation/khttp/build/tmp/test/work -Dorg.gradle.native=false -Dotel.javaagent.add-thread-details=false -Dotel.javaagent.debug=true -Dotel.javaagent.experimental.initializer.jar=/Users/aanuraag/git/splunk-otel-java/instrumentation/khttp/build/libs/agent-testing.jar -Dotel.javaagent.testing.additional-library-ignores.enabled=false -Dotel.javaagent.testing.fail-on-context-leak=true -Dotel.javaagent.testing.transform-safe-logging.enabled=true -javaagent:/Users/aanuraag/git/splunk-otel-java/testing/agent-for-testing/build/libs/agent-for-testing-1.3.0-SNAPSHOT-all.jar --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=JP -Duser.language=en -Duser.variant -ea", process.executable.path="/Users/aanuraag/Library/Java/JavaVirtualMachines/adopt-openjdk-11.0.10/Contents/Home:bin:java", process.pid=68181, process.runtime.description="AdoptOpenJDK OpenJDK 64-Bit Server VM 11.0.10+9", process.runtime.name="OpenJDK Runtime Environment", process.runtime.version="11.0.10+9", service.name="unknown_service:java", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.4.1"}}, internalHasEnded=true}, io.opentelemetry.instrumentation.testing.junit.http.AbstractHttpClientTest$$Lambda$726/0x0000000800798c40@18d02035)
error: 
Expecting actual not to be null
	at io.opentelemetry.sdk.testing.assertj.TracesAssert.hasTracesSatisfyingExactly(TracesAssert.java:53)
	at io.opentelemetry.instrumentation.testing.InstrumentationTestRunner.waitAndAssertTraces(InstrumentationTestRunner.java:75)
	at io.opentelemetry.instrumentation.testing.junit.http.AbstractHttpClientTest.successfulGetRequest(AbstractHttpClientTest.java:158)
	... 1 more
```

**Comment by joel-costigliola** [comment]
Thanks for the feedback, there is room for improvement indeed.
