### ISSUE TITLE
InjectSoftAssertions doesn't work as expected when parallel mode is enabled.

### ISSUE THREAD

**Issue by Rusgallaz** [assertj/assertj-core#2356]
#### Summary
Framework: Junit 5
Using InjectSoftAssertions and running tests in concurrent mode are leading to incorrect test results. Tests that should have failed are eventually passed.

#### Example

```java
@ExtendWith(SoftAssertionsExtension.class)
public class SoftAssertionTest {

    @InjectSoftAssertions private SoftAssertions softAssertions;

    @Test
    @DisplayName("Test 1")
    void test1() {
        softAssertions.assertThat("Test 1").as("Test 1").isEqualTo("Fail");
    }

    @Test
    @DisplayName("Test 2")
    void test2() {
        softAssertions.assertThat("Test 2").as("Test 2").isEqualTo("Fail");
    }
}
```
Both tests should fail, but one of them passes and the other fails with two errors(from test one and test two).

Screenshot from IDE
![image](https://user-images.githubusercontent.com/39244350/135622106-aa2564fa-d18d-4fe5-b9a3-c6f09c35a539.png)

If i disable parallel mode in the junit-platfrom.properties or set these two annotations 
```java
    @TestInstance(TestInstance.Lifecycle.PER_CLASS)
    @Execution(ExecutionMode.CONCURRENT)
```
it will help. But this is not a solution for me.

Repository to reproduce the issue. You can run tests by maven or from IDE. The result will be the same.

#### Version 
assertj-core  3.21.0

**Comment by joel-costigliola** [comment]
Thanks for reporting this issue with great details!

**Comment by kriegfrj** [comment]
I'll try and have a look at this one next week.

**Comment by JamesPeters98** [comment]
This is still an issue as of 3.23.1, any chance it can be looked at as it seems like this issue got missed :)

**Comment by scordio** [comment]
Hi @JamesPeters98, we'll do our best to keep this issue in scope for 3.24.0.

**Comment by kriegfrj** [comment]
> I'll try and have a look at this one next week.

Sorry, that has been an extremely long week. Hopefully it will get shorter in the coming... errmm... weeks...

**Comment by etrandafir93** [comment]
This is similar to #3550. It appears that a single test thread entering afterTestExecution collects all assertion errors and reports them together, while other tests with no errors are shown as passing (green).

If handled correctly, this could resolve #3550, though I’m not sure of the exact approach. 

One simple solution would be to use the thread-local collector (currently used for isPerClassConcurrent(ctx)) more broadly — to cover all concurrent cases (also per method + concurrent). However, I'm not sure of all the possible implications of this change.

**Comment by uzytkownik-anonimowy** [comment]
## @InjectSoftAssertions field injection shares SoftAssertions instance across concurrent test methods (PER_METHOD + parallel mode.default=concurrent)

### Description

When using `@InjectSoftAssertions` field injection with JUnit 6 (or 5) parallel execution enabled globally via `junit-platform.properties` (`mode.default=concurrent`) and `per_method` test instance lifecycle, soft assertion failures are **misattributed to wrong test methods**. Assertions collected during `testA()` are reported as failures of `testB()` (or vice versa).

This does **not** occur with parameter injection (`void test(SoftAssertions softly)`), which correctly creates a new instance per invocation.

### Root Cause

`SoftAssertionsExtension.postProcessTestInstance()` stores the `SoftAssertions` instance in the **class-level** `ExtensionContext.Store` via `getSoftAssertionsProvider()` → `getOrComputeIfAbsent()`. Even though `per_method` lifecycle creates a new test instance object for each method, all instances receive a reference to the **same** `SoftAssertions` object from the shared class-level store.

In `beforeEach()`, the extension walks up the context hierarchy and calls `setDelegate(collector)` on that shared instance — but with `mode.default=concurrent`, multiple test methods from the same class run simultaneously, causing a **race condition** on the delegate:

1. T1: `beforeEach(test1)` → `sharedSoftly.setDelegate(collector1)`
2. T2: `beforeEach(test2)` → `sharedSoftly.setDelegate(collector2)` — **overwrites**
3. T1: `softly.assertThat(...)` — assertion is now routed to `collector2`
4. `afterTestExecution(test2)` → `assertAll(collector2)` throws errors that belong to `test1`

The existing `ThreadLocalErrorCollector` protection only activates for `PER_CLASS + @Execution(CONCURRENT)` (explicit annotation). It does **not** activate when concurrency is set globally via `junit.jupiter.execution.parallel.mode.default=concurrent`:

```java
// SoftAssertionsExtension.java
static boolean isAnnotatedConcurrent(ExtensionContext context) {
    return findAnnotation(context.getRequiredTestClass(), Execution.class)
        .map(Execution::value)
        .map(x -> x == ExecutionMode.CONCURRENT)
        .orElse(false);  // ← does NOT check global configuration property
}
```

The code comment at line 361 states:

> *"if we are running "per-method", then every test gets its own instance and again there won't be any concurrency issues"*

This assumption is incorrect — `per_method` creates separate test *object instances*, but `getSoftAssertionsProvider()` returns the same `SoftAssertions` *object* from the class-level store, and `mode.default=concurrent` allows multiple methods to execute simultaneously.

### Comparison: Field Injection vs Parameter Injection

| Mechanism | Instance creation | Thread-safe with concurrent? |
|---|---|---|
| `@InjectSoftAssertions` (field) | `getOrComputeIfAbsent()` in class-level store → **shared** | ❌ No |
| Parameter injection (`void test(SoftAssertions softly)`) | `ReflectionSupport.newInstance()` per invocation → **unique** | ✅ Yes |

```java
// resolveParameter() — correctly creates a NEW instance every time:
public Object resolveParameter(ParameterContext parameterContext, ExtensionContext extensionContext) {
    SoftAssertionsProvider provider = ReflectionSupport.newInstance(providerType); // ← new instance
    provider.setDelegate(getAssertionErrorCollector(extensionContext));            // ← method-scoped
    return provider;
}
```

### Reproducer

**junit-platform.properties:**

```properties
junit.jupiter.execution.parallel.enabled=true
junit.jupiter.execution.parallel.mode.default=concurrent
junit.jupiter.execution.parallel.mode.classes.default=concurrent
junit.jupiter.execution.parallel.config.strategy=dynamic
junit.jupiter.testinstance.lifecycle.default=per_method
```

**Test class:**

```java
@ExtendWith(SoftAssertionsExtension.class)
class ReproducerTest {

    @InjectSoftAssertions
    SoftAssertions softly;

    @Test
    void test1() throws Exception {
        Thread.sleep(2000); // simulate slow I/O
        softly.assertThat("test1-value").as("test1 assertion").isEqualTo("test1-value");
    }

    @Test
    void test2() throws Exception {
        Thread.sleep(2000);
        softly.assertThat("test2-value").as("test2 assertion").isEqualTo("WRONG");
    }

    @Test
    void test3() throws Exception {
        Thread.sleep(2000);
        softly.assertThat("test3-value").as("test3 assertion").isEqualTo("test3-value");
    }
}
```

**Expected:** `test2` fails with "test2 assertion", `test1` and `test3` pass.

**Actual:** Assertion failures from `test2` may appear under `test1` or `test3` (non-deterministic, depends on thread scheduling). In real-world scenarios with long-running tests (e.g., Awaitility polling for 45 seconds), the race window is large enough that misattribution occurs consistently.

### Stack Trace Signature

When misattribution occurs via ForkJoinPool work-stealing, the stack trace contains:

```
at ForkJoinTask.doExec(ForkJoinTask.java:511)
at ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1490)
at ForkJoinPool.helpJoin(ForkJoinPool.java:2248)
at ForkJoinTask.awaitDone(ForkJoinTask.java:499)
at ForkJoinTask.join(ForkJoinTask.java:666)
```

### Suggested Fix

Two possible approaches:

**Option A (minimal):** In `instantiateProvider()`, also check the global parallel configuration property, not just the `@Execution` annotation:

```java
static boolean isConcurrent(ExtensionContext context) {
    return isAnnotatedConcurrent(context)
        || context.getConfigurationParameter("junit.jupiter.execution.parallel.mode.default")
                  .map(mode -> mode.equalsIgnoreCase("concurrent"))
                  .orElse(false);
}
```

**Option B (comprehensive):** For `per_method` lifecycle, always create a new `SoftAssertionsProvider` in `postProcessTestInstance()` instead of using `getOrComputeIfAbsent()` from the class-level store — matching the behavior of `resolveParameter()`.

### Workarounds

1. Use parameter injection instead of `@InjectSoftAssertions`
2. Set `junit.jupiter.execution.parallel.mode.default=same_thread` (sacrifices intra-class parallelism)
3. Add `@Execution(ExecutionMode.SAME_THREAD)` on affected test classes

### Environment

- AssertJ 3.27.x (confirmed in source code on `main` branch as of May 2026)
- JUnit Jupiter 6.x
- Java 25

### Impact

In our integration test suite (~65 tests across 4 classes, each with 45-second Awaitility waits), approximately 7 out of 22 reported failures were misattributed to wrong test methods. This made root cause analysis significantly harder as failure messages and stack traces pointed to unrelated tests.

**Comment by joel-costigliola** [comment]
I believe this is now fixed, the test from https://github.com/Rusgallaz/SoftAssertionConcurrent fails as expected, I have run them a few times with always the same result: 

```
ERROR] Failures: 
[ERROR]   SoftAssertionTest.test1 1 assertion error:

-- error 1 --
[Test 1] 
expected: "Fail"
 but was: "Test 1"
first 3 stack trace elements:
	at com.rusgall.SoftAssertionTest.test1(SoftAssertionTest.java:18)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
35 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)

[ERROR]   SoftAssertionTest.test2 1 assertion error:

-- error 1 --
[Test 2] 
expected: "Fail"
 but was: "Test 2"
first 3 stack trace elements:
	at com.rusgall.SoftAssertionTest.test2(SoftAssertionTest.java:24)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
62 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)

[INFO] 
[ERROR] Tests run: 2, Failures: 2, Errors: 0, Skipped: 0
```

The Reproducer test also fails as expected after running it 10 times.

Having said that, it would be great to have users feedback if it completely solve the issue.

**Comment by uzytkownik-anonimowy** [comment]
@joel-costigliola 
> I believe this is now fixed [...]
> Having said that, it would be great to have users feedback if it completely solve the issue.

Thanks.
I can confirm on my site that this commit fixes the issue.
