### ISSUE TITLE
comparingOnlyFields(*fields) selects fields not by a complete match, but selects fields for comparison starting with argument

### ISSUE THREAD

**Issue by anastya** [assertj/assertj-core#2359]
#### Summary
comparingOnlyFields(*fields) selects fields not by a complete match, but selects fields for comparison starting with argument

#### Example
Example code on Kotlin:
```java
   @Test
  fun staffUpdateDeletedStaff() {
   ....
      entityAssertionWithFields(
           actualSraff,
           expectedStaff,
           "firstName", "lastName", "description", "defaultRole", "enabled", "deleted"
      )
  }

   private fun entityAssertionWithFields(actual: Any, expected: Any, vararg fields: String) {
        assertThat(actual)
            .describedAs(describe)
            .usingRecursiveComparison()
            .comparingOnlyFields(*fields)
            .isEqualTo(expected)
    }
```

At the running this test the following error is returned:
```
Expecting actual:
  Staff(id=2703, enabled=true, inviteAccepted=false, email=bot+1633407660446@test.com, firstName=Deleted staff, lastName=deleted Staff, description=Deleted, createdAt=Tue Oct 05 11:21:00 NOVT 2021, updatedAt=2021-10-05T04:21:05.863+00:00, name=First Staff Bot Name Last Staff Bot Name, deletedAt=Tue Oct 05 11:21:05 NOVT 2021, deleted=true, twofaRequireSetup=false, password=null, defaultRole=MANAGER, defaultRoleName=MANAGER, groups=null, loginProviderType=PASSWORD)
to be equal to:
  Staff(id=null, enabled=true, inviteAccepted=null, email=bot+1633407660446@test.com, firstName=Deleted staff, lastName=deleted Staff, description=Deleted, createdAt=null, updatedAt=null, name=null, deletedAt=null, deleted=true, twofaRequireSetup=null, password=null, defaultRole=MANAGER, defaultRoleName=null, groups=null, loginProviderType=null)
when recursively comparing field by field, but found the following 2 differences:

field/property 'defaultRoleName' differ:
- actual value  : "MANAGER"
- expected value: null

field/property 'deletedAt' differ:
- actual value  : 2021-10-05T11:21:05.813 (java.util.Date)
- expected value: null
```
But 'defaultRoleName' and 'deletedAt' fields are not specified for comparison.

May be is there a mistake in using these methods and something else needs to be done?
Could you please tell me how can I use it right?

Version of assertj-core - 3.21.0.

**Comment by ahunigel** [comment]
I hit the same issue 
`
field/property 'pointCategory' differ:
- actual value  : 1
- expected value: null

field/property 'pointUniqueId' differ:
- actual value  : 0L
- expected value: 605021792L

The recursive comparison was performed with this configuration:
- the comparison was performed on the following fields: unitNumber, id, name, point, responseCode, value, stringValue, sampleDataType, engUnitUniqueProtocolID
- no overridden equals methods were used in the comparison (except for java types)
- these types were compared with the following comparators:
  - java.lang.Double -> DoubleComparator[precision=1.0E-15]
  - java.lang.Float -> FloatComparator[precision=1.0E-6]
  - java.nio.file.Path -> lexicographic comparator (Path natural order)
- actual and expected objects and their fields were compared field by field recursively even if they were not of the same type, this allows for example to compare a Person to a PersonDto (call strictTypeChecking(true) to change that behavior).


	at com.ectrs.cloud.protocol.stream.GetPointValuePerUnitIT.onGetPointValue_failed_controllerReturn503(GetPointValuePerUnitIT.java:565)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:64)

`

**Comment by joel-costigliola** [comment]
I'm not completely sure to understand the issue, could you provide a reproducible test case?
once you select some fields to compare, they are compared recursively unless you specify how to compare them with a specfic equals/comparator (see https://assertj.github.io/doc/#assertj-core-recursive-comparison-comparators)

**Comment by scordio** [comment]
Currently, [`comparingOnlyFields​`](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/RecursiveComparisonAssert.html#comparingOnlyFields(java.lang.String...)) does not support partial matches.

Field names must be complete and also nested syntax is supported. Valid examples are "height" or "home.address.number".

We had this already in mind as a separate feature, I'll raise a separate issue with the details and link it here for further discussion.

**Comment by scordio** [comment]
Sorry, I overlooked the issue before, my previous comment is unrelated.

I was able to reproduce the issue.

Having:

```java
class Staff {

  private Boolean deleted;
  private ZonedDateTime deletedAt;
  private String defaultRole;
  private String defaultRoleName;

  void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }

  void setDeletedAt(ZonedDateTime deletedAt) {
    this.deletedAt = deletedAt;
  }

  void setDefaultRole(String defaultRole) {
    this.defaultRole = defaultRole;
  }

  void setDefaultRoleName(String defaultRoleName) {
    this.defaultRoleName = defaultRoleName;
  }

}
```

the following:

```java
@Test
void test() {
  Staff actual = new Staff();
  actual.setDeleted(true);
  actual.setDeletedAt(ZonedDateTime.parse("2021-10-05T04:21:05.863+00:00"));
  actual.setDefaultRole("MANAGER");
  actual.setDefaultRoleName("MANAGER");

  Staff expected = new Staff();
  expected.setDeleted(true);
  expected.setDeletedAt(null);
  expected.setDefaultRole("MANAGER");
  expected.setDefaultRoleName(null);

  assertThat(actual)
    .usingRecursiveComparison()
    .comparingOnlyFields("defaultRole", "deleted")
    .isEqualTo(expected);
}
```

yields:

```
java.lang.AssertionError: 
Expecting actual:
  org.example.custom.SoftAssertionsErrorDescriptionTest$Staff@57c03d88
to be equal to:
  org.example.custom.SoftAssertionsErrorDescriptionTest$Staff@16aa8654
when recursively comparing field by field, but found the following 2 differences:

field/property 'defaultRoleName' differ:
- actual value  : "MANAGER"
- expected value: null

field/property 'deletedAt' differ:
- actual value  : 2021-10-05T04:21:05.863Z (java.time.ZonedDateTime)
- expected value: null

The recursive comparison was performed with this configuration:
- the comparison was performed on the following fields: defaultRole, deleted
- no overridden equals methods were used in the comparison (except for java types)
- these types were compared with the following comparators:
  - java.lang.Double -> DoubleComparator[precision=1.0E-15]
  - java.lang.Float -> FloatComparator[precision=1.0E-6]
  - java.nio.file.Path -> lexicographic comparator (Path natural order)
- actual and expected objects and their fields were compared field by field recursively even if they were not of the same type, this allows for example to compare a Person to a PersonDto (call strictTypeChecking(true) to change that behavior).
```
