### ISSUE TITLE
Hibernate map (class org.hibernate.collection.internal.PersistentMap) containsOnlyKeys assertion fails

### ISSUE THREAD

**Issue by whydoievenneedthis** [assertj/assertj-core#2448]
#### Summary

The functionality was working fine in 3.19.0, it is failing with 3.21.0. The reason for the failure is that the `org.assertj.core.internal.Maps.assertContainsOnlyKeys` method changed the way it evaluates not expected keys, and it is now creating a clone of the original map. Creation of the new PersistentMap works fine, however the subsequent `putAll` method crashes:

```
failed to lazily initialize a collection, could not initialize proxy - no Session
org.hibernate.LazyInitializationException: failed to lazily initialize a collection, could not initialize proxy - no Session
	at app//org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:612)
	at app//org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:218)
	at app//org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:591)
	at app//org.hibernate.collection.internal.PersistentMap.putAll(PersistentMap.java:224)
	at app//org.assertj.core.internal.Maps.clone(Maps.java:422)
	at app//org.assertj.core.internal.Maps.getNotExpectedKeys(Maps.java:394)
	at app//org.assertj.core.internal.Maps.assertContainsOnlyKeys(Maps.java:367)
	at app//org.assertj.core.internal.Maps.assertContainsOnlyKeys(Maps.java:350)
```

#### Example

```java
assertThat(hibernateObject.getLazyLoadedMapObject())
    .containsOnlyKeys(DayOfWeek.TUESDAY, DayOfWeek.WEDNESDAY, DayOfWeek.THURSDAY);
```

**Comment by scordio** [comment]
Thanks for reporting it, @whydoievenneedthis. The fix looks quite trivial but I'd like to introduce proper testing based on Hibernate components, which might require some time. We'll try to include this fix in the upcoming 3.22.0 release.

**Comment by scordio** [comment]
@whydoievenneedthis the fix is now part of the `main` branch. As some parts of Hibernate are replaced by mocks in the tests, it would be great if you could try the fix before we officially release it.

**Comment by whydoievenneedthis** [comment]
@scordio it all looks good on my end. thanks.
