### ISSUE TITLE
Recursive comparison throws IllegalStateException when comparing Maps

### ISSUE THREAD

**Issue by blemale** [assertj/assertj-core#2475]
#### Summary

When using `usingRecursiveComparison` to compare classes containing `Map`s, we can ends up with an `IllegalStateException` due to duplicate keys. Indeed in `RecursiveComparisonDifferenceCalculator` a deep hash to index the expected map's entries, see [here](https://github.com/assertj/assertj-core/blob/main/src/main/java/org/assertj/core/api/recursive/comparison/RecursiveComparisonDifferenceCalculator.java#L513), but there is no guarantee the hashes will be unique.

#### Example

* jdk: 15.0.5 (Azul Zulu)
* assertj-core: 3.16.1

```java
import java.util.List;
import java.util.Map;
import org.assertj.core.api.Assertions;

class Scratch {

  public static void main(String[] args) {
    Assertions.assertThat(buggyMap()).usingRecursiveComparison().isEqualTo(buggyMap());
  }

  private static Map<String, List<String>> buggyMap() {
    return Map.of(
        "VMP",
        List.of(
            "OztNUFPcnceerHAppabgHT",
            "IW",
            "AfBSmPEYfOBwGzWHzQveOi",
            "dSalYEgeHNTe",
            "mXjwEZBxeimMiWrmRVePVAwWHtRXfqQyD",
            "TGgLRwnPQUbZWFr",
            "pQWceZdDmTXdyQXcJdB",
            "ProMMnAnRXg"),
        "Uko",
        List.of(
            "pUisdBNIy",
            "rfX",
            "BagGdILqDLrNRfotwKqjCVNOJxSNoYKtSgBLMEJEJymhZjZvDuwvsqBiJuJpmvWOkiuSobCjRkeWVenaqIdlltsiUMPNtKcDMOAKiRRHHfikxUnOotnJFzNjwyYrcbkNBjxlvici",
            "AR",
            "dDvIHrhSxskuTvDSdUZwoUDdxFxxaxBWkTiprWPqSPZumdoHkvwPRrecqCLagzeeOjCuSufGwLoKATVaXfIPmjYsVfGuwlyEysXwWbVfPLgbVkaPaQdcVFQfADfDKEJeuQZlKKSsfuXICYWrmOGILeuqXKZyfEXHLnGILUcWmaVRRjrSjXXnHiTXYgdkrDeLEXZnAlbIEUYSblPqOaxuvpmOS"));
  }
}
```

```
Exception in thread "main" java.lang.IllegalStateException: Duplicate key 85113 (attempted merging values Uko=[pUisdBNIy, rfX, BagGdILqDLrNRfotwKqjCVNOJxSNoYKtSgBLMEJEJymhZjZvDuwvsqBiJuJpmvWOkiuSobCjRkeWVenaqIdlltsiUMPNtKcDMOAKiRRHHfikxUnOotnJFzNjwyYrcbkNBjxlvici, AR, dDvIHrhSxskuTvDSdUZwoUDdxFxxaxBWkTiprWPqSPZumdoHkvwPRrecqCLagzeeOjCuSufGwLoKATVaXfIPmjYsVfGuwlyEysXwWbVfPLgbVkaPaQdcVFQfADfDKEJeuQZlKKSsfuXICYWrmOGILeuqXKZyfEXHLnGILUcWmaVRRjrSjXXnHiTXYgdkrDeLEXZnAlbIEUYSblPqOaxuvpmOS] and VMP=[OztNUFPcnceerHAppabgHT, IW, AfBSmPEYfOBwGzWHzQveOi, dSalYEgeHNTe, mXjwEZBxeimMiWrmRVePVAwWHtRXfqQyD, TGgLRwnPQUbZWFr, pQWceZdDmTXdyQXcJdB, ProMMnAnRXg])
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.assertj.core.api.recursive.comparison.RecursiveComparisonDifferenceCalculator.compareUnorderedMap(RecursiveComparisonDifferenceCalculator.java:483)
	at org.assertj.core.api.recursive.comparison.RecursiveComparisonDifferenceCalculator.determineDifferences(RecursiveComparisonDifferenceCalculator.java:259)
	at org.assertj.core.api.recursive.comparison.RecursiveComparisonDifferenceCalculator.determineDifferences(RecursiveComparisonDifferenceCalculator.java:188)
	at org.assertj.core.api.RecursiveComparisonAssert.determineDifferencesWith(RecursiveComparisonAssert.java:970)
	at org.assertj.core.api.RecursiveComparisonAssert.isEqualTo(RecursiveComparisonAssert.java:159)
	at Scratch.main(assertj_bug.java:8)
```

**Comment by joel-costigliola** [comment]
Thanks for reporting this @blemale!
