### ISSUE TITLE
CaseInsensitiveStringComparator fails to compare i and I in tr_TR locale

### ISSUE THREAD

**Issue by vlsi** [assertj/assertj-core#2663]
**Describe the bug**

`CaseInsensitiveStringComparator` should treat `i` and `I` equal in `tr_TR` locale.
The bug was identified via https://github.com/assertj/assertj-core/pull/2662

See CI output: https://github.com/vlsi/assertj-core/runs/6917023184?check_suite_focus=true#step:5:10831

**Test case reproducing the bug**

Run with `-Duser.country=TR -Duser.language=tr`

```java
  @Test
  void i_and_I_sould_be_equal() {
    assertThat("i").usingComparator(CaseInsensitiveStringComparator.instance).isEqualTo("I");
  }
```

```
org.opentest4j.AssertionFailedError: 
expected: "I"
 but was: "i"
when comparing values using CaseInsensitiveStringComparator
Expected :"I"
Actual   :"i"
<Click to see difference>


	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.assertj.core.error.ConstructorInvoker.newInstance(ConstructorInvoker.java:28)
	at org.assertj.core.error.ShouldBeEqual.assertionFailedError(ShouldBeEqual.java:223)
	at org.assertj.core.error.ShouldBeEqual.newAssertionError(ShouldBeEqual.java:130)
	at org.assertj.core.internal.Failures.failure(Failures.java:105)
	at org.assertj.core.internal.Objects.assertEqual(Objects.java:339)
	at org.assertj.core.api.AbstractAssert.isEqualTo(AbstractAssert.java:362)
	at org.assertj.core.api.AbstractStringAssert.isEqualTo(AbstractStringAssert.java:403)
```

**Comment by vlsi** [comment]
The solution is to replace `s1.toLowerCase().compareTo(s2.toLowerCase())` with `s1.compareToIgnoreCase(s2)` in https://github.com/assertj/assertj-core/blob/main/src/test/java/org/assertj/core/util/CaseInsensitiveStringComparator.java#L26

**Comment by scordio** [comment]
I don't recall why we have custom comparators in tests, while we could simply use `java.lang.String.CASE_INSENSITIVE_ORDER`. From my point of view, this should be the target solution.

**Comment by vlsi** [comment]
How about `org.assertj.core.internal.Strings#assertContainsIgnoringCase`?

https://github.com/assertj/assertj-core/blob/9051a958e6ab0a750bb243060aef57001ab97e6e/src/main/java/org/assertj/core/internal/Strings.java#L528-L531

I would suggest adding https://github.com/policeman-tools/forbidden-apis verification to just ban `toLowerCase()`, `toUpperCase()` and other unsafe methods: https://github.com/assertj/assertj-core/issues/2664

**Comment by scordio** [comment]
Removing the `bug` label as `CaseInsensitiveStringComparator` belongs to the test sources and does not affect AssertJ users.
