### ISSUE TITLE
Improve failure message for IterableAssert.contains* when collection size or expected size is 1

### ISSUE THREAD

**Issue by vlsi** [assertj/assertj-core#2671]
#### Feature summary

See `year: 2019` sample in https://truth.dev/comparison#failure-messages

Rule 1) When the size of the expected collection is 1, then there's no point in printing "but some elements were not found".
Of course, they were not found, and the sole element has already been displayed in "to contain.." block.

Rule 2) The same goes for the case when actual collection has size of 1. If it did not match, then there's no point in printing "and others were not expected".

#### Example

```java
    assertThat(
      Collections.singletonList(
        "year: 2019\n" +
          "month: 7\n" +
          "day: 15\n"
      )
    )
      .containsExactly(
        "year: 2019\n" +
          "month: 6\n" +
          "day: 30\n"
      );

```

Current output:

```
java.lang.AssertionError: 
Expecting actual:
  ["year: 2019
month: 7
day: 15
"]
to contain exactly (and in same order):
  ["year: 2019
month: 6
day: 30
"]
but some elements were not found: <-- should be removed as per Rule 1
  ["year: 2019
month: 6
day: 30
"]
and others were not expected: <-- should be removed as per Rule 2
  ["year: 2019
month: 7
day: 15
"]

	at org.assertj.core.error.AssertionErrorCreator.assertionError(AssertionErrorCreator.java:93)
	at org.assertj.core.internal.Failures.failure(Failures.java:126)
	at org.assertj.core.internal.Iterables.shouldContainExactlyWithDiffAssertionError(Iterables.java:1150)
	at org.assertj.core.internal.Iterables.assertContainsExactly(Iterables.java:1141)
	at org.assertj.core.api.AbstractIterableAssert.containsExactlyForProxy(AbstractIterableAssert.java:426)
	at org.assertj.core.api.AbstractIterableAssert.containsExactly(AbstractIterableAssert.java:419)
```

**Comment by NehaDadhich** [comment]
Hi, 

I think this issue should be broken down into smaller issues as `contains*` has many implementations.
